## PanelPrimaryAssignment.R -- GENERATED by 02_shared_gene_assignment.R.
## Do not edit by hand. Change PANEL_PRECEDENCE or PANEL_PRIMARY_OVERRIDE in
## 00_config.R and re-run 02; this file is rewritten from them.
## Written 2026-09-24 08:26:35.

PANEL_PRIMARY <- c(
  "Sema4d" = "Axon guidance",
  "Cxcl12" = "Axon guidance",
  "Cxcr4"  = "Axon guidance",
  "Efnb1"  = "Axon guidance",
  "Efnb2"  = "Axon guidance",
  "Epha2"  = "Axon guidance",
  "Ephb1"  = "Axon guidance",
  "Ephb4"  = "Axon guidance",
  "Gas1"   = "Axon guidance",
  "Nrp1"   = "Axon guidance",
  "Nrp2"   = "Axon guidance",
  "Ntn1"   = "Axon guidance",
  "Ntn4"   = "Axon guidance",
  "Plxna1" = "Axon guidance",
  "Plxna4" = "Axon guidance",
  "Plxnb1" = "Axon guidance",
  "Plxnb2" = "Axon guidance",
  "Reln"   = "Axon guidance",
  "Robo1"  = "Axon guidance",
  "Robo2"  = "Axon guidance",
  "Robo4"  = "Axon guidance",
  "Sema3a" = "Axon guidance",
  "Sema3c" = "Axon guidance",
  "Sema3e" = "Axon guidance",
  "Sema3f" = "Axon guidance",
  "Slit2"  = "Axon guidance",
  "Slit3"  = "Axon guidance",
  "Unc5b"  = "Axon guidance",
  "Wnt5a"  = "Axon guidance",
  "Notch1" = "Vascular/Lymphatic"   # biological override, see 00_config.R
)
